sudo: required
services:
  - docker

before_install:
  - docker build -t ekram786/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ekram786/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "eh-docker"
  env: "EhDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-468543742856"
  bucket_path: "eh-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

  





